#!/usr/bin/python
'''
Copyright 2010-2011 DIMA Research Group, TU Berlin

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 
Created on Feb 1, 2011

@author: Alexander Alexandrov <alexander.alexandrov@tu-berlin.de>
'''

import sys, os

dgenPath = os.path.abspath( __file__ )
basePath = os.path.dirname(os.path.dirname(dgenPath))
dgenName = os.path.basename(dgenPath[0:dgenPath.rfind("-frontend")])

# append ./lib/python to path
sys.path.append("%s/lib/python/vendor" % (basePath))

import myriad.dgen

def main(*args):
	try:
	
		# run script
		dgen = myriad.dgen.DGen(basePath, dgenName, sys.argv[1:])
		dgen.run()
	except:
		return 1 # something went wrong
	else:
		return 0 # exit normally
 
if __name__ == '__main__':
	sys.exit(main(*sys.argv))
